syntax

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -36,27 +36,27 @@ jobs:
 
     - name: "Unit Tests"
       run: |
-      failures=0
-      trap 'failures=$((failures+1))' ERR
+        failures=0
+        trap 'failures=$((failures+1))' ERR
 
-      yarn workspace @ndlib/gatsby-theme-marble test
-      yarn workspace site test
+        yarn workspace @ndlib/gatsby-theme-marble test
+        yarn workspace site test
 
-      if ((failures != 0)); then
-        echo "${magenta}TESTS FAILED${reset}"
-        exit 1
-      fi
+        if ((failures != 0)); then
+          echo "${magenta}TESTS FAILED${reset}"
+          exit 1
+        fi
 
     - name: "Build"
       run: yarn workspace site build
 
     - name: "Update Coverage"
       run: |
-      pushd @ndlib/gatsby-theme-marble
-      curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
-      chmod +x ./cc-test-reporter
-      ./cc-test-reporter before-build
-      npm test -- --coverage
-      ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
+        pushd @ndlib/gatsby-theme-marble
+        curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
+        chmod +x ./cc-test-reporter
+        ./cc-test-reporter before-build
+        npm test -- --coverage
+        ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
       env:
         CC_TEST_REPORTER_ID: f507ecc7b3090a909467a65b2b78de334b6e819b99b2a54c5c333e73e2c1ffbb
