actions 3.0

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -21,19 +21,42 @@ jobs:
         node-version: ${{ matrix.node-version }}
     - uses: c-hive/gha-yarn-cache@v1
 
-    - run: ./scripts/github-actions-ci.sh
+    - name: "Install"
+      run: |
+        yarn global add gatsby-cli
+        mkdir ~/.config/gatsby
+        cp ./scripts/codebuild/config.json ~/.config/gatsby/
+        yarn install
+        pushd scripts/gatsby-source-iiif/
+        yarn install
+        node getStandard.js
+        cp ../../site/.env.test" "../../site/.env.production"
+        popd
+        ls -la ./site
 
-    - run: pushd @ndlib/gatsby-theme-marble
-    - run: curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
-    - run: chmod +x ./cc-test-reporter
-    - run: ./cc-test-reporter before-build
-      env:
-        CC_TEST_REPORTER_ID: f507ecc7b3090a909467a65b2b78de334b6e819b99b2a54c5c333e73e2c1ffbb
+    - name: "Unit Tests"
+      run: |
+      failures=0
+      trap 'failures=$((failures+1))' ERR
 
-    - run: npm test -- --coverage
-      env:
-        CC_TEST_REPORTER_ID: f507ecc7b3090a909467a65b2b78de334b6e819b99b2a54c5c333e73e2c1ffbb
+      yarn workspace @ndlib/gatsby-theme-marble test
+      yarn workspace site test
 
-    - run: ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
+      if ((failures != 0)); then
+        echo "${magenta}TESTS FAILED${reset}"
+        exit 1
+      fi
+
+    - name: "Build"
+      run: yarn workspace site build
+
+    - name: "Update Coverage"
+      run: |
+      pushd @ndlib/gatsby-theme-marble
+      curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
+      chmod +x ./cc-test-reporter
+      ./cc-test-reporter before-build
+      npm test -- --coverage
+      ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
       env:
         CC_TEST_REPORTER_ID: f507ecc7b3090a909467a65b2b78de334b6e819b99b2a54c5c333e73e2c1ffbb
